sudo: required
dist: trusty

language: go

go:
  - 1.7

git:
    submodules: false

before_install:
  - pip install -U grpcio==1.0.1
  - pip install -U docopt==0.6.2
  - make dependencies

before_script:
  - make format
  - make vet

script:
  - make travis

after_success:
  - bash <(curl -s https://codecov.io/bash)
